[package]
name = "task-store-sqlite"
version = "0.2.5"
edition = "2021"

[features]
production = []

[dependencies]
base64 = "0.22"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
uuid = { version = "1", features = ["v4"] }
dirs = "6"
rusqlite = { version = "0.37", features = ["bundled"] }
serde_json = "1"
task-core = { path = "../task-core" }
